services:
  app:
    container_name: inmemoriambrasil
    build:
      context: .
    restart: unless-stopped
    env_file: .env
#    environment:
#      - CHOKIDAR_USEPOLLING=true
    #ports:
    #  - "8080:3000" # Porta exposta para desenvolvimento
    volumes:
      - .:/usr/src/app
#    command: sh -c "npm install && npx nodemon server.js"
    command: sh -c "npm install --omit=dev && node server.js"
    depends_on:
      - mongo
    networks:
      - proxy

  mongo:
    image: mongo:7
    container_name: inmemoriambrasil-mongo
    restart: unless-stopped
    volumes:
      - ./data/mongo:/data/db
    networks:
      - proxy

networks:
  proxy:
    external: true
